### ISSUE TITLE
Plugin fails to run after latest release: Version 9  

### ISSUE THREAD

**Issue by seanehalpin** [alexwidua/figma-beautiful-shadows#1] opened 2022-02-25 12:48 UTC
Hi there

Love the plugin! Excellent work.

I believe I've encountered some breaking changes after the latest release, version 9. Below is a screenshot of my console log:

![Screen Shot 2022-02-25 at 12 44 55 PM](https://user-images.githubusercontent.com/4663244/155717523-018af656-ae9b-4518-95a8-85cbf8bf8d97.png)

Steps to recreate:

1. Run plugin
2. Plugin fails to run, no errors are presented to user.

**Comment by alexwidua** [comment] 2022-02-25 12:53
Hi @seanehalpin,
thank you for opening the issue!

- Do you open the plugin 'from scratch' or do you have a element selected when running the plugin?
- Does this happen in every file?
- Are you using the Figma web or desktop version (+ which OS)?

Cheers,
Alex

**Comment by seanehalpin** [comment] 2022-02-25 13:01
Hey Alex,

After a littler further digging:

1. The plugin works at the highest level frame
2. It will not work on any nested frames and returns the following error

![Screen Shot 2022-02-25 at 12 58 53 PM](https://user-images.githubusercontent.com/4663244/155719291-f307483a-a9b9-40b7-aea5-549828e65c3d.png)

Example of my folder structure:
![Screen Shot 2022-02-25 at 12 58 45 PM](https://user-images.githubusercontent.com/4663244/155719250-8b030bc6-fd18-4bff-a796-7dfe256eef19.png)

In the above, it works on `Window` but throws an error on each other frame.

I am using Figma desktop 107.1

Hope that helps!

**Comment by alexwidua** [comment] 2022-02-25 13:16
Hi Sean,
thanks for digging further. Unfortunately I cannot reproduce the error on my end (or maybe I didn't replicate your element).

/A

Edit: removed link to file

**Comment by sethw8** [comment] 2022-02-28 22:58
I'm able to run the plug-in sometimes. Only when I have nothing selected. And then I can drag around the shadow, but the Apply button is disabled.

**Comment by alexwidua** [comment] 2022-03-01 05:38
Hi @sethw8,
The greyed out button when nothing is selected works as intended.

Do you run into the same issue as @seanehalpin? (Plug-in not starting or crashing right after start up). 
- If yes, does it happen on every element or just specific ones? 
- and would you be able to help me reproduce the elements you're having problems with

**Edit:**
I could replicate a similar error and published a new Version 10 which potentially fixes the error. Could you check again if the plugin is working now? (also pinging @seanehalpin )

**Comment by sethw8** [comment] 2022-03-01 19:52
Yes, I understand how the plugin works. I've been using it every day since installing. The latest Figma Beta and this build are not working as well together. And the plugin never has an active Apply button for me anymore.

**Comment by alexwidua** [comment] 2022-03-01 22:03
Hi @sethw8,
I was able to track down a bug which I likely introduced in one of the recent builds. I published a new version (12) and hope that it fixes your problem. It seems to work on my end (Figma 107.1 and Figma Beta 109.6 / macOS).

/A ✌️

**Comment by sethw8** [comment] 2022-03-02 00:53
Fixed! Thank you!! 🙏

**Comment by alexwidua** [comment] 2022-03-02 09:41
Amazing. Thank you for taking your time to bring this up and I'm glad that you're using the plugin everyday :-)

I'm closing this issue for now because I assume that it solves OP's issue as well. /A

**Closed as completed by alexwidua** 2022-03-02 09:41 UTC
Labels: bug
